### ISSUE TITLE
无法处理 BV1CJ4m1b7Ep

### ISSUE THREAD

**Issue by mokurin000** [xiaohuangren1001/Bilibili-av-bv-converter#1]
```python
>>> avbv.bv2av("BV1CJ4m1b7Ep")
```
```text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/home/venv/lib/python3.11/site-packages/avbv/avbv.py", line 49, in bv2av
    if r < 0: raise TypeError('Illegal bvid')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Illegal bvid
```

今天偶然在arch群有群友用 tg-url-anti-track 时报错

**Comment by mokurin000** [comment]
avid=1250142265 > 2^30

**Comment by mokurin000** [comment]
https://github.com/Colerar/abv/
可以根据这里的算法实现
